[package]
name = "abbrev"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["Luca P. <@girasole123>"]
license = "GPL-3.0-or-later"
description = "Define, categorize, expand, and list abbreviations, acronyms, initialisms, and symbols in Typst documents."
repository = "https://github.com/girasole123/Abbrev"
keywords = ["abbreviations", "acronyms", "glossary", "symbols", "initialisms", "custom", "list", "outline"]
categories = ["text", "model"]
exclude = ["example.typ", "exemple2.typ"]
