name: Compile Typst to PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.2.0
      
      - uses: typst-community/setup-typst@v5
      
      - name: Compile Typst to PDF
        run: typst compile example.typ
      
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: pdf-output
          path: example.pdf
